matrix:
  include:
  - language: java
    jdk: oraclejdk8
    before_script:
    - cd se.qxx.jukebox
  - language: android
    sudo: true
    
    env:
      global:
      - RELEASE_STORE_FILE=${TRAVIS_BUILD_DIR}/ci/keystore
      - RELEASE_KEY_ALIAS=android-signing      
      - secure: "FK8obuni3nXduWE41SFAOul6j2G8rnrsuqibgbjha2r6NzzDagH60guqnYJJQVKdE538LHsF80wVZJLVR8eYLqP/Z64tneootX+72fEuN5kWvLoAXP79eW+faDxl9dGhiXbtscqc3wLvSIV+De9gmeg3rB9ZQCZ1NQ8JbhGo2+7m162iTtnyoB7qz2+nwhZ8t0WcUUkIJF8wpjA564mCjyGTIz7eJIcP0pj0HtPsyQYx5XwGJWCoz3L2FjRXwaF6oW0bza/q79Q/veu6bBzmpTWFGO8w6N3/LlMYNbk77ftQE4ILDo/1OJBX3h0zEHL21bA3Rwyl59g2vNg5kxzMEhSHI9fs6qF1Q5Lr09QcQx4FXFecWJ2MouQwcRAq8gGVGo0BEcjDygQXN/8mTCujuGIS0d4RrLbr+AYPYsHewCvMpUGJ/zMLTs1pOkJO/Vj4QibLfIBrcSzMppnQNOAql/WviB1QP2d/ROx02oz72Dan++j3F5yd/tKQOkd5gZn3dZBqXSDloihfAd5/FHzKFgFgx+E8POSkWDGfKv9lEvdmscMEapX8yl9TnRjbN/+tOon0Yv0DEVd9S3CuqmfW4KjR8IWZbwHSSDS68FoqYlEa3YEhOYH9cghM2rurCYIoerDpz45RzpcU1xsz6QMZpt0QSYYklXw4StLgcmmQM44="
      - secure: "wLxDWvKpkDfH7jeQhhJscVBlISTD3o3evWpiitSvlP2FRpk8zfFXP4AKFvzPklbTemBI3F8ZMSgwuR4QTsszkAOQuc60lufDMR9keoLswNWziBvhoEadJQEQDKtjB/WEhV+suwkzNxNKcm8JBs/YJ9EyzqxP9QyP5nBtibaQsV5cNzRmNdQUPGbUn9jHU8eB7ZbgMSr7Asx18QIP2zckHdTCMpP/Ggac3SBX8+RVmCKmCionvSmQp6DLzDsczZLvGiUMuAzRLEKcuZb+SJ4F3/vEJUb4HZP2iD+RpRpKVEw29jJbraVzfqrfV6KQEYY19HkF5ORGlwJTkierLR+S3cojmh2Q1woDEbGS5yKinWCsjnucaB+JfjUSpzczBl1e6dRk5reDi/37CCWvJfc+T/9A4ZLCC0e5a1uochBgmnWi70GRN/zQT0Tr9c7IHcwmp3FaboxKigtHnsuz1wgsZz7+Bxo7hEHX+ApV0UXSIIYgylvu4Gf5ZidBsCV+tbPRkMPiwUp9eGnrzqSQJzygC6oeNZf7+N66p+UDPvryRt4keZ9e5QN9cGgeHfCL+ZBj8p2HTQCVgVyg07Djru5iRQcezy0BoVXsHOFo6jHItn7UMqG6LqrtDHCMXllQIwQxDRiaVbmjYkLeAElCfXNf3jfv4IpiHoIO2l+Q44JhN3c="
      - secure: "whQp3bWvou8Ho3D1++C5gG0BX/2nav5vwrTyfOtG2BpiqcoX6lSZbRxLDggBMgA8+kqQ0NuQC+QzGEUUSQ9+enE5eb5IyOxw4MgFsVI13czchUYy5OitOhA9TqGWM36mxKCwLHvLmVbQ+lpBBv9OmFNP3vX58ytQZyq7Nj2FzEEpYncFKYMxy4WMlSFlhOr2bTzNwC1kNpieClBuzM/hhOh4hVEAH6zdpj1yLQCWGnhMiS9Xx3a7fVn2JqH6MEEoSPvGsH/7zhDF2eIUpesL4nP8QwW79Rzm4KNbRbcgBeMT1RDr1PP2chnyRgQlzs/N7tmCQUnsdjC8mDwKGU9NdHYGuZSgiU2C3guKvoKKbqqN254hy16Yq1qPE15rztySFKGO52aVJcplIrjaRuu4lsz908KembMYFM+f3xA62sRgd11IyiqCtKn1psI29W9RGNhBARk877Bj/Ponix8D1GKQYCuC74SxCJUKrOAB3NZ2jmTfSPpzYuZthgz2pINZ3NQ/5LhSB2uzRgyltCtmwXXvhNwYFwK2t+dU6Dhbrzn7u+0jMlPMWhhy25oooCRMjscnSyVvVHK0dWqOiF86FFioJ1sF/4qU+AS9EVjMqYkuuVy//m4AceofJgYJFqOwsBU5tJhQ+HF6sZoU2ffKxvqQ7z8Swjseghy2WQK6hTA="
    
    before_install:
    - chmod +x ./se.qxx.android.jukebox/gradlew
    - chmod +x ci/decrypt_files.sh
    - chmod +x install-protobuf.sh
    - "./install-protobuf.sh"
    - "./ci/decrypt_files.sh"
      
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    - rm -f  $HOME/.gradle/caches/3.3/classAnalysis/classAnalysis.lock
    - rm -f  $HOME/.gradle/caches/3.3/jarSnapshots/jarSnapshots.*
    
    cache:
      directories:
      - "$HOME/.m2"
      - "$TRAVIS_BUILD_DIR/protobuf-2.4.1"
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
      
    before_script:
    - cd se.qxx.android.jukebox
    
    android:
      components:
      - tools
      - tools
      - platform-tools
      - build-tools-25.0.0
      - android-23
      - addon_google_apis-google-23
      - extra-android-m2repository
      licenses:
      - android.sdk-license-.+
