matrix:
  include:
  - language: java
    jdk: oraclejdk8

    before_install:
     - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/ci:$LD_LIBRARY_PATH
     - unzip ci/protoc.zip -d ci
     - chmod 775 ci/*.sh
     - if [ ! -d ~/.m2 ]; then mkdir ~/.m2; fi
     - cp ci/settings.xml ~/.m2    

    before_script:
    - cd se.qxx.jukebox

    install: true

    script: ci/build.sh    

    before_deploy:
     - ls -la target
     - export RELEASE_PKG_FILE=`find target/ -name '*.jar' -exec basename {} \;`
     - export GIT_BASE=$HOME
     - echo "Deploying ${RELEASE_PKG_FILE} to GitHub releases"
     - ./ci/git-tag.sh

    deploy:
      skip_cleanup: true
      provider: releases
      api_key:
        secure: vHL4QV+9xH+8QSCk5pSEAA3we5ly9u0ZXYxHnWK4PmgK2rZQKCmZdWpiNa/96X6ZjJo$
      file_glob: true
      file: "target/${RELEASE_PKG_FILE}"

      on:
        tags: false
        branch: master

    branches:
      except:
        - /^*-v[0-9]/

  - language: android
    sudo: false
    
    before_install:
    - chmod +x ./se.qxx.android.jukebox/gradlew
    - chmod +x ci/decrypt_files.sh
    - chmod +x install-protobuf.sh
    - "./install-protobuf.sh"
    - "./ci/decrypt_files.sh"
      
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    - rm -f  $HOME/.gradle/caches/3.3/classAnalysis/classAnalysis.lock
    - rm -f  $HOME/.gradle/caches/3.3/jarSnapshots/jarSnapshots.*
    
    before_deploy:
    - "./ci/createtag.sh"
    
    #deploy:
    #  skip_cleanup: true
    #  provider: releases
    #  api_key:
    #    secure: [redacted]
    #  file_glob: true
    #  file:
    #    - file: "build/xxx/yyy*.apk"
    #  on:
    #    tags: false
    #    all_branches: true
    
    cache:
      directories:
      - "$HOME/.m2"
      - "$TRAVIS_BUILD_DIR/protobuf-2.4.1"
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
      
    before_script:
    - cd se.qxx.android.jukebox
    
    android:
      components:
      - tools
      - tools
      - platform-tools
      - build-tools-25.0.0
      - android-23
      - addon_google_apis-google-23
      - extra-android-m2repository
      licenses:
      - android.sdk-license-.+

env:
  global:
  - RELEASE_STORE_FILE=${TRAVIS_BUILD_DIR}/ci/keystore
  - RELEASE_KEY_ALIAS=android-signing      
  - secure: meX6bjHhNkTd0F0k13IHB9RkMC29bMqx0YJdapJe2hDXNgA1LIC964zHl6xkYmFHmuenuBSPfsWy2gJr3NsehJs6eMxzFNRHorx2w7lsMoBt6NSQZA5MX68zMCEyff3Z4ja2jXFI0hLYIVlGS7C/TQffTc5bWey9+ydEi9F+ixGTgfxEBVmiJXErAEjECMUOFZE0m/uR178HvHm+S4CJPC46jVd68Ix38eHS17jw+2/WEG9NOrFtqfuYfIxyuF1ju9zGLCWd+MsDt/rT5QMBHkcLNY1Wu8GkGIYv4aCvMIh2jRxrBDjDTQpyQWtkv0IKQRN8ne4CGyvi91Mezwr7wv7BSOXjh+pz+O22udX4wfDbvCFhq+GM7cbEfQ8zGtcwYvo+UX+tQf/zUBok0caE9KnuGeDN9ggvQ//JWJ0QTu+sbAVStEzW0eAY/3cxvQp1wtKkeUNMouYgTG1YB3YRDLLZ9dx3lSEmo6Ozaw5sqsNPy4I+VCEMXYfhceNArx1tFvxGlcuhmk3DKycxSOt56tL1KeIvcrUF8cY5X8M/qjnom0KgPhzFZVnMfW/NUQH8ciRykp7zkPHSxecWwTIzRMi7BkZb9KIrrymG77TbkskiGBhAvqJWBsTG1CF5bB2qaO55BKf2JV8Jua00jNRf+yIEG6oBatBBxBoDumzGemA=
  - secure: JDFxF25hwyhg0b71E1qmwtwfF0am1Lge9ZW74xiEHyoXrt3thYhU+oesEQB1aPx2AHm3mcx+MqvWmonotzvULSK80419XqlMVigIPrV0Gjfx9Q0Tav6xLx+MB4n0h5LODPxjxRe0iKMwEWixSHobIIokDVh7YOR4ffqRiqdyRMQ+jAQTsq9TsC74UYuiSjR3v2cA5aNZiJ4NfPq/HAP/yAF26NpGXHnUkremvyuhJdQTV6rHtUwJOAVgqu4OcK4zwKEOlrmRcmWqsedGIfSnqEwnt1LGDTqTWoGpBKcJLXWwTGlzmoTNH5ZJv1+fMhJqTACJga7gOctBSInyQXoVMBRtfgRj9R9XblwpTeJUJdR6glXQkK6M0DPfqOTrDJxaBnpoXMnse0pn9HPZK4yHqS1JNPekN93E8yT3ABsd95Xg+6AEseirbWVzljPXGqHiZ5k1jKpEAc4fzmDf2oDhakFTVsSi/jIy7KFPIju+l3ZFWtrvYbp2gzQ8zP9nbc4+Abt+sI4R677CVdb4hntUah3YbBy8S7O1Zw14fjO3ekspSQ/0crR9TDCI/grSC6Uz3G9RgNZOcAP9HRqnnY2RUf/XNssh+Od/vPE25y6oMq1tA3P7LMxKiZCybBD8TBxUFmuIogTlspsuH/JcCFe8yL59q3LyyQje1buBcSZh0EI=
  - secure: HojpuIUuN08cnb0vw2xz5uLp+loYoYC0+o5wyYAZo2Hb69aKJnwvkYXlCbcSklfMW7AT/GBUy4XNJiEPZnwafhDtANVE459kqOZ/rzuG23lAVIN3mbyY84k371sen/69h32GmWR8Ecf1T77rKhgKmX6LfHdmyxzIyJ6RYbn17QShgL8AwBoV384T9gD+lsazzsn+HOKRaDjEXaYYIAmVLfwTc5ckoIKb+lf03AzOOFo0r5Js3aENWWV72oMrpn9bV8a8Or7A/It8otWHvfWHg/TBstgr4xQxw/DM5M3+nKt2+K1eM/5zMoMNknr4i3AdAB7H39Xwv83DRws4VFxo8gTwc1PMw8YhOxRJ5C+QXr1BLbSJ5DAaDmUtqugu+SAlLal2ckszAoNU5x/ZGemhs3QfQkuFzcUTjcdF+4YhC5NQsiYIpdPHcEa4x2QPwuHKnR2GxoqajKh9VZ/ZS4mducndYstPLTQa0ARKWtth9jTJd1NRGzHz/J9lpAjJKt7LE0SoNymHpcqFSZ1Kr8rW6VMIo0/llEJu0BM9cSRLUTXjQ/hh4OhDO1S6GahJCv2lhQtMTa7EHavfQARgyMSlCXHNwS/egfKRScfwNiF5WMGy0rbWQUOtxLDt+k6/+dLFT3ojIxS75L+xWgmrsa3fzJDnx11Mp8IrtoyeYu0aE3c=
  - secure: l5nfXSCC7qVgACbHU256siS3g3YsmaM0LYU64hj9h9lFQ94CGQNQvv6TEprNmYhaPw3ucluYB09RB8AtlUhyY7tOuQUYLSGvedp+4xiwfkiYd1rhNkSNF2p77uGK9KABtL7/fKvVjaEfiURfrHpAFsyRRFkJbp0hkrnUQY7S2N9h+p2leiFhfeA44Rh0P4IWH2r14x3SQdKPQzAjhxGWbln/kRIIr9bpUphsx53yiJoZWH5ig9JuAHSFdMuPIvEuFqgQyeRMzwhCzLUmtccThh1Cxx2yWAvAPtio7mqUknRdBZ12hStowjXBW338lxMMF/mgSqsmETlXkPUtTGmCBSAf1x5LuQTg2rKUwyqaQP72b52DGo8guJVR6YvtyjwpBPEnXWy8ZvPmbTnnWSo8VNMisIcn1BEJ7p6CguSohzKqjrBGvuqoNPVKcvRCEu845IglMTOaOD8JZXqKViRjz4/T3J3fJzM16XRHrP6wvoUAQWy8R8ZmS1JSaKUGJMOWphjRbnlxYrexRNwi7WjWp8373qnev9ujfLXFW1FQMo0BGTmiHXPkiTAaRWvbSK38h8MgkQJ/AHo6W8Dbu+GORn2aBYy5p3oChnYp4w7q6ReG83UiG/tG5mICPlAJgAdSQ+nsoag3u7pb0Q/PZf7SaGTDUPYra7uuz8vzCFIuauk=
  - secure: BX6qJgIHsvfdfrAyG+GfNWSpHoUXX70me9a/oHGGxGSxrnk9XpwMr3YPXagzFZCu/DMRgqwTAE5Wuypyf5/+m9ocPTondMbNGXbeIhAECY9NrJ3Z7kWUOl8Qxg+7t8E1i3COGYV3yqqMUir/FY+1DxIniiTMwHY1cs6PQs50vUVppmaB4mSxLLIuKOASzEZJY8/4iDxKJdilBG2RfLpd3IhN1Hd2cJeU4jNRoREqhwUB/QagQv6hDtDP19qi7IonuyeeZj73YIwjqHN9bD4zwNcOiNrAC4kgg3tNi/fuYHERbLsb9HGN++NoCez07pQYXsFyMcUkezTls89klEcRZAT8Hn6OFnE0qFLfjF3I5wLdXgNMYtA9H8yR4QEfJwvxeKF3HlP7KMoHYVQP4KlV2Usg3DID2AIhsvDsfvQH2P4nVwKqvvWCQtyD8Dxj4RU5XgZmZPQkjM6ZiwK1f7AHrW/IbIhXYJ2Jfo3fxVTYKSWCMgDJEGc4E0Tpk1DM8udKL7ox8GuOec0OaRVETpGu6lPHDbm48y3QgMtrUw5As5lrITugz0wr/AJKL33dtnrtx4gbvfmYvkjHo2nrBI9U7AYnIJCr9Ki6nmBTx1OWsE9Qb91JcOPoOPC/88SzBolBXmeYO88amBNduzpMaAlYiD+uPmqEk3K3o34w3ATWZuw=
