deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT # <--------both used
  tag_name: $TRAVIS_TAG # <--------both used
  name: hello-netcoreapp $TRAVIS_TAG
  body: Automated release from Travis CI with added files from AppVeyor build
  draft: true
  file_glob: true
  file:
    - artifacts/*.tar.gz # FDDs and SCDs
    - artifacts/*.AppImage # AppImage
  api_key:
    secure: [removed for brevity]
  on:
    tags: true
