sudo: true
matrix: 
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd se.qxx.jukebox

    - language: android

      before_script:
        - cd se.qxx.android.jukebox
      android:
        components:
          - tools
          - tools
          - platform-tools
          - build-tools-25.0.0
          - android-23
          - addon_google_apis-google-23
          - extra-android-m2repository
        licenses:
          - android.sdk-license-.+
