// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        maven { url "https://raw.githubusercontent.com/krussan/maven-repo/master/" }
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.12.0'
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.5'
        classpath 'com.github.triplet.gradle:play-publisher:3.12.1'
    }
}

ext {
    jukeboxVersion = '0.46.3'
    grpcVersion = '1.66.0'
}

allprojects {
    repositories {
    	google()
        mavenCentral()
        maven {
            url "https://raw.githubusercontent.com/krussan/maven-repo/master/"
        }
    }
}

tasks.register('outputVersion') {
    new File(projectDir, "version.txt").text = jukeboxVersion
}
