package se.qxx.jukebox.domain.dao;

import se.qxx.dao.db.SQLiteDatabase;

import java.util.Map;

import se.qxx.dao.AbstractDao;
import se.qxx.dao.AbstractDaoSession;
import se.qxx.dao.identityscope.IdentityScopeType;
import se.qxx.dao.internal.DaoConfig;

import se.qxx.jukebox.domain.JukeboxDomain.Movie;
import se.qxx.jukebox.domain.JukeboxDomain.Season;
import se.qxx.jukebox.domain.JukeboxDomain.Subtitle;
import se.qxx.jukebox.domain.JukeboxDomain.Media;

import se.qxx.jukebox.domain.dao.MovieDao;
import se.qxx.jukebox.domain.dao.SeasonDao;
import se.qxx.jukebox.domain.dao.SubtitleDao;
import se.qxx.jukebox.domain.dao.MediaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see se.qxx.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieDaoConfig;
    private final DaoConfig seasonDaoConfig;
    private final DaoConfig subtitleDaoConfig;
    private final DaoConfig mediaDaoConfig;

    private final MovieDao movieDao;
    private final SeasonDao seasonDao;
    private final SubtitleDao subtitleDao;
    private final MediaDao mediaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieDaoConfig = daoConfigMap.get(MovieDao.class).clone();
        movieDaoConfig.initIdentityScope(type);

        seasonDaoConfig = daoConfigMap.get(SeasonDao.class).clone();
        seasonDaoConfig.initIdentityScope(type);

        subtitleDaoConfig = daoConfigMap.get(SubtitleDao.class).clone();
        subtitleDaoConfig.initIdentityScope(type);

        mediaDaoConfig = daoConfigMap.get(MediaDao.class).clone();
        mediaDaoConfig.initIdentityScope(type);

        movieDao = new MovieDao(movieDaoConfig, this);
        seasonDao = new SeasonDao(seasonDaoConfig, this);
        subtitleDao = new SubtitleDao(subtitleDaoConfig, this);
        mediaDao = new MediaDao(mediaDaoConfig, this);

        registerDao(Movie.class, movieDao);
        registerDao(Season.class, seasonDao);
        registerDao(Subtitle.class, subtitleDao);
        registerDao(Media.class, mediaDao);
    }
    
    public void clear() {
        movieDaoConfig.getIdentityScope().clear();
        seasonDaoConfig.getIdentityScope().clear();
        subtitleDaoConfig.getIdentityScope().clear();
        mediaDaoConfig.getIdentityScope().clear();
    }

    public MovieDao getMovieDao() {
        return movieDao;
    }

    public SeasonDao getSeasonDao() {
        return seasonDao;
    }

    public SubtitleDao getSubtitleDao() {
        return subtitleDao;
    }

    public MediaDao getMediaDao() {
        return mediaDao;
    }

}
