package se.qxx.jukebox.domain.dao;

import se.qxx.dao.db.Cursor;
import se.qxx.dao.db.SQLiteDatabase;
import se.qxx.dao.db.SQLiteStatement;

import se.qxx.dao.AbstractDao;
import se.qxx.dao.Property;
import se.qxx.dao.internal.DaoConfig;

import se.qxx.jukebox.domain.JukeboxDomain.Media;
import se.qxx.jukebox.domain.JukeboxDomain.Media.Builder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MEDIA.
*/
public class MediaDao extends AbstractDao<Media, Void> {

    public static final String TABLENAME = "MEDIA";

    /**
     * Properties of entity Media.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Index = new Property(0, Integer.class, "Index", false, "INDEX");
        public final static Property ID = new Property(1, Integer.class, "ID", false, "ID");
        public final static Property MetaDuration = new Property(2, Integer.class, "MetaDuration", false, "META_DURATION");
    };


    public MediaDao(DaoConfig config) {
        super(config);
    }
    
    public MediaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MEDIA' (" + //
                "'INDEX' INTEGER," + // 0: Index
                "'ID' INTEGER," + // 1: ID
                "'META_DURATION' INTEGER);"); // 2: MetaDuration
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MEDIA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Media entity) {
        stmt.clearBindings();
        if(entity.hasIndex()) {
            stmt.bindLong(1, entity.getIndex());
        }
        if(entity.hasID()) {
            stmt.bindLong(2, entity.getID());
        }
        if(entity.hasMetaDuration()) {
            stmt.bindLong(3, entity.getMetaDuration());
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Media readEntity(Cursor cursor, int offset) {
        Builder builder = Media.newBuilder();
        if (!cursor.isNull(offset + 0)) {
            builder.setIndex(cursor.getInt(offset + 0));
        }
        if (!cursor.isNull(offset + 1)) {
            builder.setID(cursor.getInt(offset + 1));
        }
        if (!cursor.isNull(offset + 2)) {
            builder.setMetaDuration(cursor.getInt(offset + 2));
        }
        return builder.build();
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Media entity, int offset) {
        throw new UnsupportedOperationException("Protobuf objects cannot be modified");
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Media entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Media entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return false;
    }
    
}
