//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 08:14:53 em CEST 
//


package se.qxx.jukebox.settings.imdb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="searchUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="searchPatterns" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="searchResultPattern" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="blockPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="recordPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="groupBlock" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="groupRecordUrl" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="groupRecordYear" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="infoPatterns" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="infoPattern" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="settings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="preferredTitleLanguage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchUrl",
    "searchPatterns",
    "infoPatterns",
    "settings"
})
@XmlRootElement(name = "imdb")
public class Imdb {

    @XmlElement(required = true)
    protected String searchUrl;
    protected Imdb.SearchPatterns searchPatterns;
    protected Imdb.InfoPatterns infoPatterns;
    @XmlElement(required = true)
    protected Imdb.Settings settings;

    /**
     * Gets the value of the searchUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchUrl() {
        return searchUrl;
    }

    /**
     * Sets the value of the searchUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchUrl(String value) {
        this.searchUrl = value;
    }

    /**
     * Gets the value of the searchPatterns property.
     * 
     * @return
     *     possible object is
     *     {@link Imdb.SearchPatterns }
     *     
     */
    public Imdb.SearchPatterns getSearchPatterns() {
        return searchPatterns;
    }

    /**
     * Sets the value of the searchPatterns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imdb.SearchPatterns }
     *     
     */
    public void setSearchPatterns(Imdb.SearchPatterns value) {
        this.searchPatterns = value;
    }

    /**
     * Gets the value of the infoPatterns property.
     * 
     * @return
     *     possible object is
     *     {@link Imdb.InfoPatterns }
     *     
     */
    public Imdb.InfoPatterns getInfoPatterns() {
        return infoPatterns;
    }

    /**
     * Sets the value of the infoPatterns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imdb.InfoPatterns }
     *     
     */
    public void setInfoPatterns(Imdb.InfoPatterns value) {
        this.infoPatterns = value;
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Imdb.Settings }
     *     
     */
    public Imdb.Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imdb.Settings }
     *     
     */
    public void setSettings(Imdb.Settings value) {
        this.settings = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="infoPattern" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "infoPattern"
    })
    public static class InfoPatterns {

        protected List<Imdb.InfoPatterns.InfoPattern> infoPattern;

        /**
         * Gets the value of the infoPattern property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the infoPattern property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInfoPattern().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Imdb.InfoPatterns.InfoPattern }
         * 
         * 
         */
        public List<Imdb.InfoPatterns.InfoPattern> getInfoPattern() {
            if (infoPattern == null) {
                infoPattern = new ArrayList<Imdb.InfoPatterns.InfoPattern>();
            }
            return this.infoPattern;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "regex"
        })
        public static class InfoPattern {

            @XmlElement(required = true)
            protected String regex;
            @XmlAttribute
            protected String type;
            @XmlAttribute
            protected Integer group;

            /**
             * Gets the value of the regex property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegex() {
                return regex;
            }

            /**
             * Sets the value of the regex property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegex(String value) {
                this.regex = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the group property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGroup() {
                return group;
            }

            /**
             * Sets the value of the group property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGroup(Integer value) {
                this.group = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="searchResultPattern" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="blockPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="recordPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="groupBlock" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="groupRecordUrl" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="groupRecordYear" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "searchResultPattern"
    })
    public static class SearchPatterns {

        protected List<Imdb.SearchPatterns.SearchResultPattern> searchResultPattern;

        /**
         * Gets the value of the searchResultPattern property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the searchResultPattern property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSearchResultPattern().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Imdb.SearchPatterns.SearchResultPattern }
         * 
         * 
         */
        public List<Imdb.SearchPatterns.SearchResultPattern> getSearchResultPattern() {
            if (searchResultPattern == null) {
                searchResultPattern = new ArrayList<Imdb.SearchPatterns.SearchResultPattern>();
            }
            return this.searchResultPattern;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="blockPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="recordPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="groupBlock" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="groupRecordUrl" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="groupRecordYear" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "blockPattern",
            "recordPattern"
        })
        public static class SearchResultPattern {

            @XmlElement(required = true)
            protected String blockPattern;
            @XmlElement(required = true)
            protected String recordPattern;
            @XmlAttribute
            protected String name;
            @XmlAttribute
            protected Boolean enabled;
            @XmlAttribute
            protected Integer priority;
            @XmlAttribute
            protected Integer groupBlock;
            @XmlAttribute
            protected Integer groupRecordUrl;
            @XmlAttribute
            protected Integer groupRecordYear;

            /**
             * Gets the value of the blockPattern property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBlockPattern() {
                return blockPattern;
            }

            /**
             * Sets the value of the blockPattern property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBlockPattern(String value) {
                this.blockPattern = value;
            }

            /**
             * Gets the value of the recordPattern property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordPattern() {
                return recordPattern;
            }

            /**
             * Sets the value of the recordPattern property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordPattern(String value) {
                this.recordPattern = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the enabled property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isEnabled() {
                return enabled;
            }

            /**
             * Sets the value of the enabled property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setEnabled(Boolean value) {
                this.enabled = value;
            }

            /**
             * Gets the value of the priority property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPriority() {
                return priority;
            }

            /**
             * Sets the value of the priority property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPriority(Integer value) {
                this.priority = value;
            }

            /**
             * Gets the value of the groupBlock property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGroupBlock() {
                return groupBlock;
            }

            /**
             * Sets the value of the groupBlock property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGroupBlock(Integer value) {
                this.groupBlock = value;
            }

            /**
             * Gets the value of the groupRecordUrl property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGroupRecordUrl() {
                return groupRecordUrl;
            }

            /**
             * Sets the value of the groupRecordUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGroupRecordUrl(Integer value) {
                this.groupRecordUrl = value;
            }

            /**
             * Gets the value of the groupRecordYear property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGroupRecordYear() {
                return groupRecordYear;
            }

            /**
             * Sets the value of the groupRecordYear property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGroupRecordYear(Integer value) {
                this.groupRecordYear = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="preferredTitleLanguage" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Settings {

        @XmlAttribute
        protected String preferredTitleLanguage;

        /**
         * Gets the value of the preferredTitleLanguage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreferredTitleLanguage() {
            return preferredTitleLanguage;
        }

        /**
         * Sets the value of the preferredTitleLanguage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreferredTitleLanguage(String value) {
            this.preferredTitleLanguage = value;
        }

    }

}
