//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.11 at 10:53:49 PM CET 
//


package se.qxx.jukebox.settings.imdb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="settings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="sleepSecondsMin" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="sleepSecondsMax" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="debug" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="title">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="titleResultPattern" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="blockPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="recordPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="groupBlock" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="groupRecordTitle" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="groupRecordCountry" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="preferredLanguage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="useOriginalIfExists" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="searchUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="searchPatterns" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="searchResultPattern" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="blockPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="recordPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="enabled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="priority" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="groupBlock" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="groupRecordUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="groupRecordYear" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="tvPattern" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="infoPatterns" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="infoPattern" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" type="{}InfoPatternType" />
 *                           &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="episodePatterns" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="episodePattern" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="episodeGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="airDateGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="urlGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="titleGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datePatterns" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "settings",
    "title",
    "searchUrl",
    "searchPatterns",
    "infoPatterns",
    "episodePatterns",
    "datePatterns"
})
@XmlRootElement(name = "imdb")
public class Imdb {

    @XmlElement(required = true)
    protected Imdb.Settings settings;
    @XmlElement(required = true)
    protected Imdb.Title title;
    @XmlElement(required = true)
    protected String searchUrl;
    protected Imdb.SearchPatterns searchPatterns;
    protected Imdb.InfoPatterns infoPatterns;
    protected Imdb.EpisodePatterns episodePatterns;
    protected Imdb.DatePatterns datePatterns;

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Imdb.Settings }
     *     
     */
    public Imdb.Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imdb.Settings }
     *     
     */
    public void setSettings(Imdb.Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Imdb.Title }
     *     
     */
    public Imdb.Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imdb.Title }
     *     
     */
    public void setTitle(Imdb.Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the searchUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchUrl() {
        return searchUrl;
    }

    /**
     * Sets the value of the searchUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchUrl(String value) {
        this.searchUrl = value;
    }

    /**
     * Gets the value of the searchPatterns property.
     * 
     * @return
     *     possible object is
     *     {@link Imdb.SearchPatterns }
     *     
     */
    public Imdb.SearchPatterns getSearchPatterns() {
        return searchPatterns;
    }

    /**
     * Sets the value of the searchPatterns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imdb.SearchPatterns }
     *     
     */
    public void setSearchPatterns(Imdb.SearchPatterns value) {
        this.searchPatterns = value;
    }

    /**
     * Gets the value of the infoPatterns property.
     * 
     * @return
     *     possible object is
     *     {@link Imdb.InfoPatterns }
     *     
     */
    public Imdb.InfoPatterns getInfoPatterns() {
        return infoPatterns;
    }

    /**
     * Sets the value of the infoPatterns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imdb.InfoPatterns }
     *     
     */
    public void setInfoPatterns(Imdb.InfoPatterns value) {
        this.infoPatterns = value;
    }

    /**
     * Gets the value of the episodePatterns property.
     * 
     * @return
     *     possible object is
     *     {@link Imdb.EpisodePatterns }
     *     
     */
    public Imdb.EpisodePatterns getEpisodePatterns() {
        return episodePatterns;
    }

    /**
     * Sets the value of the episodePatterns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imdb.EpisodePatterns }
     *     
     */
    public void setEpisodePatterns(Imdb.EpisodePatterns value) {
        this.episodePatterns = value;
    }

    /**
     * Gets the value of the datePatterns property.
     * 
     * @return
     *     possible object is
     *     {@link Imdb.DatePatterns }
     *     
     */
    public Imdb.DatePatterns getDatePatterns() {
        return datePatterns;
    }

    /**
     * Sets the value of the datePatterns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imdb.DatePatterns }
     *     
     */
    public void setDatePatterns(Imdb.DatePatterns value) {
        this.datePatterns = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pattern"
    })
    public static class DatePatterns {

        protected List<String> pattern;

        /**
         * Gets the value of the pattern property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pattern property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPattern().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPattern() {
            if (pattern == null) {
                pattern = new ArrayList<String>();
            }
            return this.pattern;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="episodePattern" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="episodeGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="airDateGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="urlGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="titleGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "episodePattern"
    })
    public static class EpisodePatterns {

        protected List<Imdb.EpisodePatterns.EpisodePattern> episodePattern;

        /**
         * Gets the value of the episodePattern property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the episodePattern property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEpisodePattern().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Imdb.EpisodePatterns.EpisodePattern }
         * 
         * 
         */
        public List<Imdb.EpisodePatterns.EpisodePattern> getEpisodePattern() {
            if (episodePattern == null) {
                episodePattern = new ArrayList<Imdb.EpisodePatterns.EpisodePattern>();
            }
            return this.episodePattern;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="episodeGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="airDateGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="urlGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="titleGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "regex"
        })
        public static class EpisodePattern {

            @XmlElement(required = true)
            protected String regex;
            @XmlAttribute(name = "episodeGroup", required = true)
            protected int episodeGroup;
            @XmlAttribute(name = "airDateGroup", required = true)
            protected int airDateGroup;
            @XmlAttribute(name = "urlGroup", required = true)
            protected int urlGroup;
            @XmlAttribute(name = "titleGroup", required = true)
            protected int titleGroup;

            /**
             * Gets the value of the regex property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegex() {
                return regex;
            }

            /**
             * Sets the value of the regex property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegex(String value) {
                this.regex = value;
            }

            /**
             * Gets the value of the episodeGroup property.
             * 
             */
            public int getEpisodeGroup() {
                return episodeGroup;
            }

            /**
             * Sets the value of the episodeGroup property.
             * 
             */
            public void setEpisodeGroup(int value) {
                this.episodeGroup = value;
            }

            /**
             * Gets the value of the airDateGroup property.
             * 
             */
            public int getAirDateGroup() {
                return airDateGroup;
            }

            /**
             * Sets the value of the airDateGroup property.
             * 
             */
            public void setAirDateGroup(int value) {
                this.airDateGroup = value;
            }

            /**
             * Gets the value of the urlGroup property.
             * 
             */
            public int getUrlGroup() {
                return urlGroup;
            }

            /**
             * Sets the value of the urlGroup property.
             * 
             */
            public void setUrlGroup(int value) {
                this.urlGroup = value;
            }

            /**
             * Gets the value of the titleGroup property.
             * 
             */
            public int getTitleGroup() {
                return titleGroup;
            }

            /**
             * Sets the value of the titleGroup property.
             * 
             */
            public void setTitleGroup(int value) {
                this.titleGroup = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="infoPattern" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="type" type="{}InfoPatternType" />
     *                 &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "infoPattern"
    })
    public static class InfoPatterns {

        protected List<Imdb.InfoPatterns.InfoPattern> infoPattern;

        /**
         * Gets the value of the infoPattern property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the infoPattern property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInfoPattern().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Imdb.InfoPatterns.InfoPattern }
         * 
         * 
         */
        public List<Imdb.InfoPatterns.InfoPattern> getInfoPattern() {
            if (infoPattern == null) {
                infoPattern = new ArrayList<Imdb.InfoPatterns.InfoPattern>();
            }
            return this.infoPattern;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="type" type="{}InfoPatternType" />
         *       &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "regex"
        })
        public static class InfoPattern {

            @XmlElement(required = true)
            protected String regex;
            @XmlAttribute(name = "type")
            protected InfoPatternType type;
            @XmlAttribute(name = "group")
            protected Integer group;

            /**
             * Gets the value of the regex property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegex() {
                return regex;
            }

            /**
             * Sets the value of the regex property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegex(String value) {
                this.regex = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link InfoPatternType }
             *     
             */
            public InfoPatternType getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link InfoPatternType }
             *     
             */
            public void setType(InfoPatternType value) {
                this.type = value;
            }

            /**
             * Gets the value of the group property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGroup() {
                return group;
            }

            /**
             * Sets the value of the group property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGroup(Integer value) {
                this.group = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="searchResultPattern" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="blockPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="recordPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="enabled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="priority" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="groupBlock" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="groupRecordUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="groupRecordYear" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="tvPattern" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "searchResultPattern"
    })
    public static class SearchPatterns {

        protected List<Imdb.SearchPatterns.SearchResultPattern> searchResultPattern;

        /**
         * Gets the value of the searchResultPattern property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the searchResultPattern property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSearchResultPattern().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Imdb.SearchPatterns.SearchResultPattern }
         * 
         * 
         */
        public List<Imdb.SearchPatterns.SearchResultPattern> getSearchResultPattern() {
            if (searchResultPattern == null) {
                searchResultPattern = new ArrayList<Imdb.SearchPatterns.SearchResultPattern>();
            }
            return this.searchResultPattern;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="blockPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="recordPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="enabled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="priority" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="groupBlock" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="groupRecordUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="groupRecordYear" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="tvPattern" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "blockPattern",
            "recordPattern"
        })
        public static class SearchResultPattern {

            @XmlElement(required = true)
            protected String blockPattern;
            @XmlElement(required = true)
            protected String recordPattern;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "enabled", required = true)
            protected boolean enabled;
            @XmlAttribute(name = "priority", required = true)
            protected int priority;
            @XmlAttribute(name = "groupBlock", required = true)
            protected int groupBlock;
            @XmlAttribute(name = "groupRecordUrl", required = true)
            protected int groupRecordUrl;
            @XmlAttribute(name = "groupRecordYear", required = true)
            protected int groupRecordYear;
            @XmlAttribute(name = "tvPattern", required = true)
            protected boolean tvPattern;

            /**
             * Gets the value of the blockPattern property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBlockPattern() {
                return blockPattern;
            }

            /**
             * Sets the value of the blockPattern property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBlockPattern(String value) {
                this.blockPattern = value;
            }

            /**
             * Gets the value of the recordPattern property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordPattern() {
                return recordPattern;
            }

            /**
             * Sets the value of the recordPattern property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordPattern(String value) {
                this.recordPattern = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the enabled property.
             * 
             */
            public boolean isEnabled() {
                return enabled;
            }

            /**
             * Sets the value of the enabled property.
             * 
             */
            public void setEnabled(boolean value) {
                this.enabled = value;
            }

            /**
             * Gets the value of the priority property.
             * 
             */
            public int getPriority() {
                return priority;
            }

            /**
             * Sets the value of the priority property.
             * 
             */
            public void setPriority(int value) {
                this.priority = value;
            }

            /**
             * Gets the value of the groupBlock property.
             * 
             */
            public int getGroupBlock() {
                return groupBlock;
            }

            /**
             * Sets the value of the groupBlock property.
             * 
             */
            public void setGroupBlock(int value) {
                this.groupBlock = value;
            }

            /**
             * Gets the value of the groupRecordUrl property.
             * 
             */
            public int getGroupRecordUrl() {
                return groupRecordUrl;
            }

            /**
             * Sets the value of the groupRecordUrl property.
             * 
             */
            public void setGroupRecordUrl(int value) {
                this.groupRecordUrl = value;
            }

            /**
             * Gets the value of the groupRecordYear property.
             * 
             */
            public int getGroupRecordYear() {
                return groupRecordYear;
            }

            /**
             * Sets the value of the groupRecordYear property.
             * 
             */
            public void setGroupRecordYear(int value) {
                this.groupRecordYear = value;
            }

            /**
             * Gets the value of the tvPattern property.
             * 
             */
            public boolean isTvPattern() {
                return tvPattern;
            }

            /**
             * Sets the value of the tvPattern property.
             * 
             */
            public void setTvPattern(boolean value) {
                this.tvPattern = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="sleepSecondsMin" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="sleepSecondsMax" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="debug" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Settings {

        @XmlAttribute(name = "sleepSecondsMin", required = true)
        protected int sleepSecondsMin;
        @XmlAttribute(name = "sleepSecondsMax", required = true)
        protected int sleepSecondsMax;
        @XmlAttribute(name = "debug")
        protected Boolean debug;

        /**
         * Gets the value of the sleepSecondsMin property.
         * 
         */
        public int getSleepSecondsMin() {
            return sleepSecondsMin;
        }

        /**
         * Sets the value of the sleepSecondsMin property.
         * 
         */
        public void setSleepSecondsMin(int value) {
            this.sleepSecondsMin = value;
        }

        /**
         * Gets the value of the sleepSecondsMax property.
         * 
         */
        public int getSleepSecondsMax() {
            return sleepSecondsMax;
        }

        /**
         * Sets the value of the sleepSecondsMax property.
         * 
         */
        public void setSleepSecondsMax(int value) {
            this.sleepSecondsMax = value;
        }

        /**
         * Gets the value of the debug property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isDebug() {
            if (debug == null) {
                return false;
            } else {
                return debug;
            }
        }

        /**
         * Sets the value of the debug property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setDebug(Boolean value) {
            this.debug = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="titleResultPattern" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="blockPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="recordPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="groupBlock" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="groupRecordTitle" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="groupRecordCountry" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="preferredLanguage" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="useOriginalIfExists" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "titleResultPattern"
    })
    public static class Title {

        protected Imdb.Title.TitleResultPattern titleResultPattern;
        @XmlAttribute(name = "preferredLanguage")
        protected String preferredLanguage;
        @XmlAttribute(name = "useOriginalIfExists")
        protected Boolean useOriginalIfExists;

        /**
         * Gets the value of the titleResultPattern property.
         * 
         * @return
         *     possible object is
         *     {@link Imdb.Title.TitleResultPattern }
         *     
         */
        public Imdb.Title.TitleResultPattern getTitleResultPattern() {
            return titleResultPattern;
        }

        /**
         * Sets the value of the titleResultPattern property.
         * 
         * @param value
         *     allowed object is
         *     {@link Imdb.Title.TitleResultPattern }
         *     
         */
        public void setTitleResultPattern(Imdb.Title.TitleResultPattern value) {
            this.titleResultPattern = value;
        }

        /**
         * Gets the value of the preferredLanguage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreferredLanguage() {
            return preferredLanguage;
        }

        /**
         * Sets the value of the preferredLanguage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreferredLanguage(String value) {
            this.preferredLanguage = value;
        }

        /**
         * Gets the value of the useOriginalIfExists property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isUseOriginalIfExists() {
            return useOriginalIfExists;
        }

        /**
         * Sets the value of the useOriginalIfExists property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUseOriginalIfExists(Boolean value) {
            this.useOriginalIfExists = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="blockPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="recordPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="groupBlock" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="groupRecordTitle" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="groupRecordCountry" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "blockPattern",
            "recordPattern"
        })
        public static class TitleResultPattern {

            @XmlElement(required = true)
            protected String blockPattern;
            @XmlElement(required = true)
            protected String recordPattern;
            @XmlAttribute(name = "groupBlock")
            protected Integer groupBlock;
            @XmlAttribute(name = "groupRecordTitle")
            protected Integer groupRecordTitle;
            @XmlAttribute(name = "groupRecordCountry")
            protected Integer groupRecordCountry;

            /**
             * Gets the value of the blockPattern property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBlockPattern() {
                return blockPattern;
            }

            /**
             * Sets the value of the blockPattern property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBlockPattern(String value) {
                this.blockPattern = value;
            }

            /**
             * Gets the value of the recordPattern property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordPattern() {
                return recordPattern;
            }

            /**
             * Sets the value of the recordPattern property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordPattern(String value) {
                this.recordPattern = value;
            }

            /**
             * Gets the value of the groupBlock property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGroupBlock() {
                return groupBlock;
            }

            /**
             * Sets the value of the groupBlock property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGroupBlock(Integer value) {
                this.groupBlock = value;
            }

            /**
             * Gets the value of the groupRecordTitle property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGroupRecordTitle() {
                return groupRecordTitle;
            }

            /**
             * Sets the value of the groupRecordTitle property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGroupRecordTitle(Integer value) {
                this.groupRecordTitle = value;
            }

            /**
             * Gets the value of the groupRecordCountry property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGroupRecordCountry() {
                return groupRecordCountry;
            }

            /**
             * Sets the value of the groupRecordCountry property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGroupRecordCountry(Integer value) {
                this.groupRecordCountry = value;
            }

        }

    }

}
