//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.05 at 12:11:53 AM CEST 
//


package se.qxx.jukebox.settings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.qxx.jukebox.settings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.qxx.jukebox.settings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings }
     * 
     */
    public JukeboxListenerSettings createJukeboxListenerSettings() {
        return new JukeboxListenerSettings();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Logs }
     * 
     */
    public JukeboxListenerSettings.Logs createJukeboxListenerSettingsLogs() {
        return new JukeboxListenerSettings.Logs();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Players }
     * 
     */
    public JukeboxListenerSettings.Players createJukeboxListenerSettingsPlayers() {
        return new JukeboxListenerSettings.Players();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.TcpListener }
     * 
     */
    public JukeboxListenerSettings.TcpListener createJukeboxListenerSettingsTcpListener() {
        return new JukeboxListenerSettings.TcpListener();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Builders }
     * 
     */
    public JukeboxListenerSettings.Builders createJukeboxListenerSettingsBuilders() {
        return new JukeboxListenerSettings.Builders();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.StringSplitters }
     * 
     */
    public JukeboxListenerSettings.StringSplitters createJukeboxListenerSettingsStringSplitters() {
        return new JukeboxListenerSettings.StringSplitters();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.StringSplitters.Splitter }
     * 
     */
    public JukeboxListenerSettings.StringSplitters.Splitter createJukeboxListenerSettingsStringSplittersSplitter() {
        return new JukeboxListenerSettings.StringSplitters.Splitter();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.StringSplitters.Splitter.Groups }
     * 
     */
    public JukeboxListenerSettings.StringSplitters.Splitter.Groups createJukeboxListenerSettingsStringSplittersSplitterGroups() {
        return new JukeboxListenerSettings.StringSplitters.Splitter.Groups();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.StringSplitters.Episodes }
     * 
     */
    public JukeboxListenerSettings.StringSplitters.Episodes createJukeboxListenerSettingsStringSplittersEpisodes() {
        return new JukeboxListenerSettings.StringSplitters.Episodes();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.StringSplitters.Episodes.Pattern }
     * 
     */
    public JukeboxListenerSettings.StringSplitters.Episodes.Pattern createJukeboxListenerSettingsStringSplittersEpisodesPattern() {
        return new JukeboxListenerSettings.StringSplitters.Episodes.Pattern();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.StringSplitters.Episodes.Pattern.Groups }
     * 
     */
    public JukeboxListenerSettings.StringSplitters.Episodes.Pattern.Groups createJukeboxListenerSettingsStringSplittersEpisodesPatternGroups() {
        return new JukeboxListenerSettings.StringSplitters.Episodes.Pattern.Groups();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.StringSplitters.Parts }
     * 
     */
    public JukeboxListenerSettings.StringSplitters.Parts createJukeboxListenerSettingsStringSplittersParts() {
        return new JukeboxListenerSettings.StringSplitters.Parts();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.SubFinders }
     * 
     */
    public JukeboxListenerSettings.SubFinders createJukeboxListenerSettingsSubFinders() {
        return new JukeboxListenerSettings.SubFinders();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.SubFinders.SubFinder }
     * 
     */
    public JukeboxListenerSettings.SubFinders.SubFinder createJukeboxListenerSettingsSubFindersSubFinder() {
        return new JukeboxListenerSettings.SubFinders.SubFinder();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.SubFinders.SubFinder.SubFinderSettings }
     * 
     */
    public JukeboxListenerSettings.SubFinders.SubFinder.SubFinderSettings createJukeboxListenerSettingsSubFindersSubFinderSubFinderSettings() {
        return new JukeboxListenerSettings.SubFinders.SubFinder.SubFinderSettings();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Catalogs }
     * 
     */
    public JukeboxListenerSettings.Catalogs createJukeboxListenerSettingsCatalogs() {
        return new JukeboxListenerSettings.Catalogs();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Catalogs.Catalog }
     * 
     */
    public JukeboxListenerSettings.Catalogs.Catalog createJukeboxListenerSettingsCatalogsCatalog() {
        return new JukeboxListenerSettings.Catalogs.Catalog();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Catalogs.Catalog.Extensions }
     * 
     */
    public JukeboxListenerSettings.Catalogs.Catalog.Extensions createJukeboxListenerSettingsCatalogsCatalogExtensions() {
        return new JukeboxListenerSettings.Catalogs.Catalog.Extensions();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Catalogs.Catalog.LocalPaths }
     * 
     */
    public JukeboxListenerSettings.Catalogs.Catalog.LocalPaths createJukeboxListenerSettingsCatalogsCatalogLocalPaths() {
        return new JukeboxListenerSettings.Catalogs.Catalog.LocalPaths();
    }

    /**
     * Create an instance of {@link ExcludeType }
     * 
     */
    public ExcludeType createExcludeType() {
        return new ExcludeType();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Logs.Log }
     * 
     */
    public JukeboxListenerSettings.Logs.Log createJukeboxListenerSettingsLogsLog() {
        return new JukeboxListenerSettings.Logs.Log();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Players.Server }
     * 
     */
    public JukeboxListenerSettings.Players.Server createJukeboxListenerSettingsPlayersServer() {
        return new JukeboxListenerSettings.Players.Server();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.TcpListener.Port }
     * 
     */
    public JukeboxListenerSettings.TcpListener.Port createJukeboxListenerSettingsTcpListenerPort() {
        return new JukeboxListenerSettings.TcpListener.Port();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Builders.Builder }
     * 
     */
    public JukeboxListenerSettings.Builders.Builder createJukeboxListenerSettingsBuildersBuilder() {
        return new JukeboxListenerSettings.Builders.Builder();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.StringSplitters.Splitter.Groups.Group }
     * 
     */
    public JukeboxListenerSettings.StringSplitters.Splitter.Groups.Group createJukeboxListenerSettingsStringSplittersSplitterGroupsGroup() {
        return new JukeboxListenerSettings.StringSplitters.Splitter.Groups.Group();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.StringSplitters.Episodes.Pattern.Groups.Group }
     * 
     */
    public JukeboxListenerSettings.StringSplitters.Episodes.Pattern.Groups.Group createJukeboxListenerSettingsStringSplittersEpisodesPatternGroupsGroup() {
        return new JukeboxListenerSettings.StringSplitters.Episodes.Pattern.Groups.Group();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.StringSplitters.Parts.PartPattern }
     * 
     */
    public JukeboxListenerSettings.StringSplitters.Parts.PartPattern createJukeboxListenerSettingsStringSplittersPartsPartPattern() {
        return new JukeboxListenerSettings.StringSplitters.Parts.PartPattern();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.SubFinders.SubFinder.SubFinderSettings.Setting }
     * 
     */
    public JukeboxListenerSettings.SubFinders.SubFinder.SubFinderSettings.Setting createJukeboxListenerSettingsSubFindersSubFinderSubFinderSettingsSetting() {
        return new JukeboxListenerSettings.SubFinders.SubFinder.SubFinderSettings.Setting();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Catalogs.Catalog.Extensions.Extension }
     * 
     */
    public JukeboxListenerSettings.Catalogs.Catalog.Extensions.Extension createJukeboxListenerSettingsCatalogsCatalogExtensionsExtension() {
        return new JukeboxListenerSettings.Catalogs.Catalog.Extensions.Extension();
    }

    /**
     * Create an instance of {@link JukeboxListenerSettings.Catalogs.Catalog.LocalPaths.Path }
     * 
     */
    public JukeboxListenerSettings.Catalogs.Catalog.LocalPaths.Path createJukeboxListenerSettingsCatalogsCatalogLocalPathsPath() {
        return new JukeboxListenerSettings.Catalogs.Catalog.LocalPaths.Path();
    }

}
