//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.23 at 09:19:11 em CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.qxx.se/jukebox/parser", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.qxx.jukebox.settings.parser;
