//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 03:38:32 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.qxx.se/jukebox/parser", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.qxx.jukebox.settings.parser;
